import AW_Logger
def make_log(log, log2):
	log.debug("This is A Debug Message")
	log2.debug("This is A Debug Message")
	log.debug("This is A Debug Message\nThat Contains\nMore Than One Line")
	log2.debug("This is A Debug Message\nThat Contains\nMore Than One Line")
	log.info("This is A Info Message")
	log2.info("This is A Info Message")
	log.info("This is A Info Message\nThat Contains\nMore Than One Line")
	log2.info("This is A Info Message\nThat Contains\nMore Than One Line")
	log.warn("This is A Warning Message")
	log2.warn("This is A Warning Message")
	log.warn("This is A Warning Message\nThat Contains\nMore Than One Line")
	log2.warn("This is A Warning Message\nThat Contains\nMore Than One Line")
	log.error("This is A Error Message")
	log2.error("This is A Error Message")
	log.error("This is A Error Message\nThat Contains\nMore Than One Line")
	log2.error("This is A Error Message\nThat Contains\nMore Than One Line")
	log.fatal("This is A Fatal Message")
	log2.fatal("This is A Fatal Message")
	log.fatal("This is A Fatal Message\nThat Contains\nMore Than One Line")
	log2.fatal("This is A Fatal Message\nThat Contains\nMore Than One Line")

logger = AW_Logger.create_Logger("AW_Base", "Maya", 10)
logger2 = AW_Logger.get_Sub_Logger("AW_Base.Scripts")
make_log(logger, logger2)